config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root 'welcome#index'

  resources :rinks, only: %i[index new create]

  resources :skates do
    resources :skaters, only: %i[index]
  end

  resources :skaters, only: %i[index show new create edit]

  resources :about, only: %i[index]
  resources :social_media, only: %i[index]

  resources :users, only: %i[index show]
  get "/login", to: "skaters#login_form"
  post "/login", to: "skaters#login"
  get "/logout", to: "skaters#logout"
  get '/auth/:provider/callback', to: 'sessions#omniauth'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kapus_skate_development.rb
class KapusSkateDevelopment < ApplicationRecord
end

app/models/rink.rb
class Rink < ApplicationRecord
  validates_presence_of :name
  # validates_presence_of :address
  # validates_presence_of :city
  # validates_presence_of :state
  # validates_presence_of :phone

  has_many :skates
end

app/models/skate.rb
class Skate < ApplicationRecord
  belongs_to :rink
  has_many :skater_skates
  has_many :skaters, through: :skater_skates

  def self.next_scheduled_skate
    today = Time.now.to_s.split[0]
    next_skate = where('date >= ?', today).order(:date).first
    next_skate.date.strftime("%A %B %d, %Y") unless next_skate.nil?
  end

  def self.next_three_skates
    today = Time.now.to_s.split[0]
    limit(3).where('date >= ?', today).order('date')
  end
end

app/models/skater.rb
class Skater < ApplicationRecord
  has_many :skater_skates
  has_many :skates, through: :skater_skates

  validates :email, presence: true
  validates :email, uniqueness: true
  validates_presence_of :password

  has_secure_password

  def self.sort_by_creation_date
    order(created_at: :desc)
  end

end

app/models/skater_skate.rb
class SkaterSkate < ApplicationRecord
  belongs_to :skater
  belongs_to :skate
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.name = response[:info][:name]
      u.email = response[:info][:email]
      u.password = SecureRandom.hex(15)
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rinks_controller.rb
class RinksController < ApplicationController
  def index
    @rinks = Rink.all
  end

  def new; end

  def create
    rink = Rink.new(rink_params)

    if rink.save
      flash[:success] = "New rink created"
      redirect_to rinks_path
    else
      render :new
    end
  end

  private

  def rink_params
    params.permit(:name, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def omniauth
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to '/login'
    end
  end
end

app/controllers/skaters_controller.rb
class SkatersController < ApplicationController
  def index
    @skaters = if params.include?(:sort)
                 Skater.order(params[:sort])
               elsif params.include?(:skater)
                 Skater.where('name like ?', "%#{params[:skater][:search_term]}%")
               else
                 Skater.sort_by_creation_date
               end
  end

  def show
    @skater = Skater.find(params[:id])
  end

  def new
    @skater = Skater.new
  end

  def create
    skater = skater_params
    skater[:email] = skater[:email].downcase
    @skater = Skater.new(skater)

    if @skater.save
      flash[:success] = "welcome #{@skater.email}"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @skater = Skater.find(params[:id])
  end

  def update
    @skater = Skater.find(params[:id])

    if @skater.update(skater_params)
      redirect_to skater_path
    else
      render :edit
    end
  end

  def destroy
    @skater = Skater.find(params[:id])
    @skater.destroy
    redirect_to skaters_path
  end

  def login_form
  end

  def login
    skater = Skater.find_by(email: params[:skater][:email])

    if !skater.nil? && skater.authenticate(params[:skater][:password])
      session[:skater_id] = skater.id unless session[:skater_id]
      flash[:success] = "Welcome, #{skater.email.downcase}!"
      redirect_to root_path
    else
      flash[:error] = "Wrong password or no user"
      render :login_form
    end
  end

  def logout
    session[:user_id] = nil
    flash[:goodbye] = "you've successfully logged out"
    redirect_to root_path
  end

  private

  def skater_params
    params.require(:skater).permit('email', 'password')
  end
end

app/controllers/skates_controller.rb
class SkatesController < ApplicationController
  def index
    today = Time.now.to_s.split[0]
    @skates = Skate.order(:date).where 'date >= ?', today
    @skate = Skate.new
    @past_skates = Skate.order(date: :desc).where("date < ?", today)
  end

  def new
    @skate = Skate.new
  end

  def show
    @skate = Skate.find(params[:id])
  end

  def edit
    @skate = Skate.find(params[:id])
  end

  def create
    @skate = Skate.new(skate_params)

    if @skate.save
      redirect_to skates_path
    else
      render 'new'
    end
  end

  def update
    @skate = Skate.find(params[:id])

    if @skate.update(skate_params)
      redirect_to @skate
    else
      render 'edit'
    end
  end

  def destroy
    @skate = Skate.find(params[:id])
    @skate.destroy

    redirect_to skates_path
  end

  private

  def skate_params
    params.require(:skate).permit(:date)
  end
end

app/controllers/social_media_controller.rb
class SocialMediaController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # cookies.delete :remember_me
    @next_skate = Skate.next_scheduled_skate
    @skate = Skate.find_by(date: @next_skate)
    @next_three_skates = Skate.next_three_skates
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skaters_helper.rb
module SkatersHelper
end

app/helpers/skates_helper.rb
module SkatesHelper
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="row justify-content-around p-3 border border-1">
  <div class="col-1 flex-1 bg-white">
    hello world
  </div>

  <div class="col-1 flex-1 bg-white">
    hello
  </div>
</div>

app/views/rinks/index.html.erb
<div class="row">
  <div class="col">
    <%= link_to 'Add Rink', "/rinks/new", class: 'btn btn-primary' %>
  </div>
</div>


<div class="row">
    <% @rinks.each do |rink| %>
  <div class="col-lg-6 col-sm-12 border border-1 d-flex flex-column align-items-center">
      <p><%= rink.name %></p>
      <p><%= rink.address %></p>
  </div>
    <% end %>
</div>

app/views/rinks/new.html.erb
<div class="row flex-column align-items-center">
<div class="col-6 text-center">
  <h3>Add a Rink</h3>
</div>
  <div class="col-6">
    <%= form_with(url: "/rinks", method: :post,  local: true) do |f| %>
      <table>
        <tr>
          <td><%= f.label :name, 'Name of Rink:' %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :address, 'Street Address:' %></td>
          <td><%= f.text_field :address %></td>
        </tr>
        <tr>
          <td><%= f.label :city, 'City' %></td>
          <td><%= f.text_field :city %></td>
        </tr>
        <tr>
          <td><%= f.label :state, 'State:' %></td>
          <td><%= f.text_field :state  %></td>
        </tr>
        <tr>
          <td><%= f.label :phone, 'Phone:' %></td>
          <td><%= f.text_field :phone %></td>
        </tr>
        <tr>
        <td> </td>
        <td><%= f.submit "Add Rink", class: 'btn btn-primary' %></td></tr>
      </table>
    <% end %>
  </div>
</div>

app/views/skaters/edit.html.erb
<h1>Skaters#edit</h1>
<p>Find me in app/views/skaters/edit.html.erb</p>
<%= render 'partials/skater_signup' %>

app/views/skaters/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-2 p-3">
      <%= link_to 'create a skater', new_skater_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="row">
    <div class="col border border-1">
      <%= form_with(scope: :skater, url: '/skaters', method: :get, local: true) do |f| %>
        <%= f.text_field :search_term, placeholder: 'search for a player' %>
        <%= f.submit 'search' %>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= render partial: 'partials/skaters' %>
  </div>
</div>

app/views/skaters/login_form.html.erb
<div class="row">
  <div class="col">
    <%= render partial: 'partials/skater_signin' %>
  </div>
</div>

app/views/skaters/logout.html.erb
<h1>Log out path</h1>

app/views/skaters/new.html.erb
<div class="row">
  <div class="col border border-1">
    <h1>Add a Skater</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-10 p-2 d-flex justify-content-center mx-auto">
    <%= render 'partials/skater_signup' %>
  </div>
</div>

app/views/skaters/show.html.erb
<%= content_tag :div, content_tag(:div, @skater.email, class: "col-6"), class: 'row' %>

app/views/skates/edit.html.erb
<h2>Update the skate using the form below</h2>
<%= render 'partials/skates' %>

app/views/skates/index.html.erb
<div class="row justify-content-center">
  <div class="col col-4">
    <h2>Upcoming skates</h2>
    <div class="col">
    </div>
  </div>
</div>
<div class="row justify-content-around">
  <div class="col-lg-6">
    <table class="table table-sm table-hover">
      <% @skates.each do |skate| %>
        <tr>
          <td><%= link_to "#{skate.date.strftime('%a %b %d, %Y')}", skate_path(skate.id), class: "text-decoration-none" %></td>
          <td><%= link_to 'edit', edit_skate_path(skate) %></td>
          <td><%= link_to 'delete', skate_path(skate), method: :delete, data: {confirm: 'are you sure?'} %></td>
        </tr>
      <% end %>
    </table>
    <div class="d-flex justify-content-center"><%= link_to 'Add a skate', new_skate_path, class: 'btn btn-primary' %></div>
  </div>
  <div class="col-lg-2 bg-light p-3">
    <table class="table">
      <th class="text-center">past skates</th>
      <% @past_skates.each do |skate| %>
        <tr>
          <td class="text-center"><%= skate.date.strftime('%a %b %d, %Y') %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/skates/new.html.erb
<div class="row">
  <div class="col">
    <h2>Add a skate using the form below</h2>
    <%= render 'partials/skates' %>
  </div>
</div>

app/views/skates/show.html.erb
<%= @skate.date %>
<%# @skate.rink_id %>

app/views/social_media/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3 class="display-3">Stay connected</h3>
      <p>If you want to continue the locker room conversation, say hi to Jim, or just find out if there's been any changes to the schedule, please drop by the Discord server and join the conversation!</p>
      <p><%= link_to 'Discord app', 'https://discord.gg/Zv5yrZZHH6', class: 'btn btn-lg btn-primary' %></p>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= "Welcome back, #{@user.name}"  %>

app/views/welcome/index.html.erb
<div class="row h-100 justify-content-center align-items-center">
  <div class="col-6 d-flex flex-column align-items-center">
    <%= button_to "Log in with Google", '/auth/google_oauth2', class: 'btn btn-primary'  %>
  </div>
</div>