config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root 'welcome#index'

  resources :rinks, only: %i[index new create]

  resources :skates do
    resources :skaters, only: %i[index]
  end

  resources :skaters, only: %i[index show new create edit]

  resources :about, only: %i[index]
  resources :social_media, only: %i[index]

  resources :users, only: %i[index show]
  get "/login", to: "skaters#login_form"
  post "/login", to: "skaters#login"
  get "/logout", to: "skaters#logout"
  get '/auth/:provider/callback', to: 'sessions#omniauth'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kapus_skate_development.rb
class KapusSkateDevelopment < ApplicationRecord
end

app/models/rink.rb
class Rink < ApplicationRecord
  validates_presence_of :name
  # validates_presence_of :address
  # validates_presence_of :city
  # validates_presence_of :state
  # validates_presence_of :phone

  has_many :skates
end

app/models/skate.rb
class Skate < ApplicationRecord
  belongs_to :rink
  has_many :skater_skates
  has_many :skaters, through: :skater_skates

  def self.next_scheduled_skate
    today = Time.now.to_s.split[0]
    next_skate = where('date >= ?', today).order(:date).first
    next_skate.date.strftime("%A %B %d, %Y") unless next_skate.nil?
  end

  def self.next_three_skates
    today = Time.now.to_s.split[0]
    limit(3).where('date >= ?', today).order('date')
  end
end

app/models/skater.rb
class Skater < ApplicationRecord
  has_many :skater_skates
  has_many :skates, through: :skater_skates

  validates :email, presence: true
  validates :email, uniqueness: true
  validates_presence_of :password

  has_secure_password

  def self.sort_by_creation_date
    order(created_at: :desc)
  end

end

app/models/skater_skate.rb
class SkaterSkate < ApplicationRecord
  belongs_to :skater
  belongs_to :skate
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.name = response[:info][:name]
      u.email = response[:info][:email]
      u.password = SecureRandom.hex(15)
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
end

app/controllers/rinks_controller.rb
class RinksController < ApplicationController
  def index
    @rinks = Rink.all
  end

  def new; end

  def create
    rink = Rink.new(rink_params)

    if rink.save
      flash[:success] = "New rink created"
      redirect_to rinks_path
    else
      render :new
    end
  end

  private

  def rink_params
    params.permit(:name, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def omniauth
    user = User.from_omniauth(request.env['omniauth.auth'])
    if user.valid?
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to '/login'
    end
  end
end

app/controllers/skaters_controller.rb
class SkatersController < ApplicationController
  def index
    @skaters = if params.include?(:sort)
                 Skater.order(params[:sort])
               elsif params.include?(:skater)
                 Skater.where('name like ?', "%#{params[:skater][:search_term]}%")
               else
                 Skater.sort_by_creation_date
               end
  end

  def show
    @skater = Skater.find(params[:id])
  end

  def new
    @skater = Skater.new
  end

  def create
    skater = skater_params
    skater[:email] = skater[:email].downcase
    @skater = Skater.new(skater)

    if @skater.save
      flash[:success] = "welcome #{@skater.email}"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @skater = Skater.find(params[:id])
  end

  def update
    @skater = Skater.find(params[:id])

    if @skater.update(skater_params)
      redirect_to skater_path
    else
      render :edit
    end
  end

  def destroy
    @skater = Skater.find(params[:id])
    @skater.destroy
    redirect_to skaters_path
  end

  def login_form
  end

  def login
    skater = Skater.find_by(email: params[:skater][:email])

    if !skater.nil? && skater.authenticate(params[:skater][:password])
      session[:skater_id] = skater.id unless session[:skater_id]
      flash[:success] = "Welcome, #{skater.email.downcase}!"
      redirect_to root_path
    else
      flash[:error] = "Wrong password or no user"
      render :login_form
    end
  end

  def logout
    session[:user_id] = nil
    flash[:goodbye] = "you've successfully logged out"
    redirect_to root_path
  end

  private

  def skater_params
    params.require(:skater).permit('email', 'password')
  end
end

app/controllers/skates_controller.rb
class SkatesController < ApplicationController
  def index
    today = Time.now.to_s.split[0]
    @skates = Skate.order(:date).where 'date >= ?', today
    @skate = Skate.new
    @past_skates = Skate.order(date: :desc).where("date < ?", today)
  end

  def new
    @skate = Skate.new
  end

  def show
    @skate = Skate.find(params[:id])
  end

  def edit
    @skate = Skate.find(params[:id])
  end

  def create
    @skate = Skate.new(skate_params)

    if @skate.save
      redirect_to skates_path
    else
      render 'new'
    end
  end

  def update
    @skate = Skate.find(params[:id])

    if @skate.update(skate_params)
      redirect_to @skate
    else
      render 'edit'
    end
  end

  def destroy
    @skate = Skate.find(params[:id])
    @skate.destroy

    redirect_to skates_path
  end

  private

  def skate_params
    params.require(:skate).permit(:date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # cookies.delete :remember_me
    @next_skate = Skate.next_scheduled_skate
    @skate = Skate.find_by(date: @next_skate)
    @next_three_skates = Skate.next_three_skates
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skaters_helper.rb
module SkatersHelper
end

app/helpers/skates_helper.rb
module SkatesHelper
end

app/helpers/social_media_helper.rb
module SocialMediaHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>KapusSkate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: 'partials/navbar' unless current_page?(root_path) %>
    <div class="container border border-1">
      <% if flash[:goodbye].present? %>
        <%= flash[:goodbye] %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, content_tag(:h1, msg), class: "#{name}") %>
<% end %>

app/views/partials/_formtag.html.erb
<%= form_tag do %>
<div>hello</div>
<% end %>

app/views/partials/_navbar.html.erb
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark"
        aria-label="Third navbar example">
        <div class="container-fluid">
          <%= link_to 'kapusSkate', root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarsExample03" aria-controls="navbarsExample03"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample03">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Skates', skates_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log out', logout_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>

app/views/partials/_next_three_skates.html.erb
<div class="col-sm-3 d-flex flex-column align-items-center">
  <table class="table">
    <tr>
      <td>
        Date:
      </td>
      <td>
        <%= link_to skate.date.strftime("%A %B %d, %Y"), skate_path(skate.id) %>
      </td>
    </tr>
  </table>
</div>

app/views/partials/_signup.html.erb
<div class="col-md-10 mx-auto col-lg-5">
        <form class="p-4 p-md-5 border rounded-3 bg-light">
          <div class="form-floating mb-3">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
          </div>
          <div class="checkbox mb-3">
            <label>
              <input type="checkbox" value="remember-me"> Remember me
            </label>
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
          <hr class="my-4">
          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
        </form>
      </div>

app/views/partials/_skate_details.html.erb
<p class="col-lg-10">Total skaters for next skate: <%= @skaters.count %><small> (as of <%= Time.now.strftime("%-m/%d %H:%M%P") %>)</small> </p>


<div class="row mb-3">
	<%# @skate.skaters.each do |skater| %>
	<%# skater %>
	<%# end %>
</div>

<div class="row mb-3 p-3">
	<% @skate.skaters.each do |skater| %>
    <%= skater.name %>
  <% end %>
</div>

app/views/partials/_skate_signup.html.erb
<%= form_with model: @skate, local: true do |f| %>
<%= f.select :date, Skate.all.collect { |x| x.date }, { class: "text-2xl"} %>
  <%= f.submit %>
<% end %>

app/views/partials/_skater_signin.html.erb
<div class="col-md-10 mx-auto col-lg-5" id="signup_form">
  <%= form_with(model: @skater, scope: :skater, url: login_path, local: true, class: 'p-4 p-md-5 border rounded-3 bg-light shadow') do |f| %>
    <%= content_tag :legend, 'Log In', class: 'display-4' %>
    <div class="form-floating mb-3">
      <%= f.text_field :email, type: 'email', class:'form-control', id: 'floatingInput', placeholder: 'email' %>
      <%= f.label :email, 'email address' %>
    </div>
    <div class="form-floating mb-3">
      <%= f.text_field :password, type: 'password', class:'form-control', id: 'floatingInput', placeholder: 'password' %>
      <%= f.label :password, 'password' %>
    </div>
    <div class="d-flex p-3 justify-content-center">
    </div>
    <%= f.submit 'Log in', class: 'btn btn-primary w-100 btn-lg' %>
  <% end %>
</div>
</div>

app/views/partials/_skater_signup.html.erb
<div class="col-md-10 mx-auto col-lg-5" id="signup_form">
  <%= form_with(model: @skater, scope: :skater, url: '/skaters', method: 'post', local: true, class: 'p-4 p-md-5 border rounded-3 bg-light shadow') do |f| %>
    <%= content_tag :legend, 'SignUp', class: 'display-4' %>
    <div class="form-floating mb-3">
      <%= f.text_field :email, type: 'email', class:'form-control', id: 'floatingInput', placeholder: 'email' %>
      <%= f.label :email, 'email address' %>
    </div>
    <div class="form-floating mb-3">
      <%= f.text_field :password, type: 'password', class:'form-control', id: 'floatingInput', placeholder: 'password' %>
      <%= f.label :password, 'password' %>
    </div>
    <div class="d-flex p-3 justify-content-center">
      <%= link_to 'I already have an account', login_path %>
    </div>
    <%= f.submit 'Sign Up', class: 'btn btn-primary w-100 btn-lg' %>
  <% end %>
</div>
</div>

app/views/partials/_skater_table_headers.html.erb
<th>email</th>
<th>edit</th>
<th>delete</th>

app/views/partials/_skater_table_row.html.erb
<td><%= link_to skater.email, skater_path(skater) %></td>
<td><%= link_to 'edit', edit_skater_path(skater), method: :get %></td>
<td><%= link_to 'delete', skater_path(skater), method: :delete, data: {confirm: 'Are you sure?'} %></td>

app/views/partials/_skaters.html.erb
<div class="col">
  <table class="table table-sm">
    <tr>
    <%= render partial: 'partials/skater_table_headers' %>
    </tr>
    <% @skaters.each do |skater| %>
      <tr>
        <%= render partial: 'partials/skater_table_row', locals: { skater: skater } %>
      </tr>
    <% end %>
  </table>
</div>

app/views/partials/_skates.html.erb
<%= form_for @skate, local: true, class: 'border border-3' do |f| %>
  <% if @skate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skate.errors.count, "error") %> prohibited this skate from being saved: </h2>
      <ul>
        <% @skate.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end%>
  <div class="row mb-3">
    <%= f.label :date, class: 'col-sm-2' %>
    <div class="col-lg-10">
      <%= f.date_field :date %>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col-sm-5">
      <%= f.submit 'add skate' %>
    </div>
  </div>
<% end %>

app/views/partials/login_form.html.erb
<div class="col-md-10 mx-auto col-lg-5" id="signup_form">
  <%= form_with(url: user_predictions_path, method: 'post', local: true, class: 'p-4 p-md-5 border rounded-3 bg-light') do |f| %>
    <%= content_tag :legend, 'SignUp', class: 'display-4' %>
    <div class="form-floating mb-3">
      <%= f.text_field :email, type: 'email', class:'form-control', id: 'floatingInput', placeholder: 'email' %>
      <%= f.label :email, 'email address' %>
    </div>
    <div class="form-floating mb-3">
      <%= f.text_field :password, type: 'password', class:'form-control', id: 'floatingInput', placeholder: 'password' %>
      <%= f.label :password, 'password' %>
    </div>
    <%= f.submit 'Sign Up', class: 'btn btn-primary w-100 btn-lg' %>
  <% end %>
</div>
</div>
<%=  %>